# Generated by Django 5.0.7 on 2024-10-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchedulerApp", "0005_alter_meetingtime_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtime",
            name="time",
            field=models.CharField(
                choices=[
                    ("6:45 - 8:20", "6:45 - 8:20"),
                    ("8:20 - 10:00", "8:20 - 10:00"),
                    ("10:00 - 10:50", "10:00 - 10:50"),
                    ("10:50 - 12:30", "10:50 - 12:30"),
                    ("12:30 - 2:10", "12:30 - 2:10"),
                ],
                default="11:30 - 12:30",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="InstructorAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="SchedulerApp.instructor",
                    ),
                ),
                (
                    "meeting_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_instructors",
                        to="SchedulerApp.meetingtime",
                    ),
                ),
            ],
        ),
    ]
