# Generated by Django 5.0.7 on 2024-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchedulerApp", "0006_alter_meetingtime_time_instructoravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="availability_end",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="instructor",
            name="availability_start",
            field=models.TimeField(null=True),
        ),
    ]
