# Generated by Django 5.0.7 on 2024-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchedulerApp", "0009_alter_meetingtime_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="max_numb_students",
        ),
        migrations.AddField(
            model_name="course",
            name="max_period",
            field=models.IntegerField(default=2),
        ),
    ]
